package reaper.android.app.config;

public enum ErrorCode
{
    INVALID_SESSION,
    EVENTS_FETCH_FAILURE,
    EVENT_UPDATES_FETCH_FAILURE,
    GOOGLE_API_CLIENT_NOT_CONNECTED,
    GOOGLE_API_LOCATION_FETCH_FAILURE,
    RSVP_UPDATE_FAILURE,
    EVENT_CREATION_FAILURE,
    EVENT_DETAILS_FETCH_FAILURE,
    EVENT_LOCATION_FETCH_FAILURE,
    EVENT_EDIT_FAILURE,
    FACEBOOK_FRIENDS_FETCH_FAILURE,
    PHONE_CONTACTS_FETCH_FAILURE,
    ALL_FACEBOOK_FRIENDS_FETCH_FAILURE;
}
