package reaper.android.app.config;

public enum ErrorCode
{
    EVENTS_FETCH_FAILURE,
    EVENT_UPDATES_FETCH_FAILURE,
    GOOGLE_API_CLIENT_NOT_CONNECTED,
    GOOGLE_API_LOCATION_FETCH_FAILURE,
    RSVP_UPDATE_FAILURE;
}
