package reaper.android.app.config;

public enum ErrorCode
{
    EVENTS_FETCH_FAILURE,
    EVENT_DETAILS_FETCH_FAILURE,
    USER_APP_FRIENDS_FETCH_FAILURE,
    PHONE_CONTACTS_FETCH_FAILURE,
    FACEBOOK_FRIENDS_FETCHED_FAILURE,
    FACEBOOK_FRIENDS_UPDATION_ON_SERVER_FAILURE,
    APP_FRIENDS_FETCH_FROM_NETWORK_FAILURE,
    PHONE_CONTACTS_FOR_SMS_FETCH_FAILURE;
}
